"""Initial database schema

Revision ID: a613f5aa7b23
Revises: 641ba22265bb
Create Date: 2025-12-06 11:17:15.035398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a613f5aa7b23'
down_revision: Union[str, Sequence[str], None] = '641ba22265bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticekts', sa.Column('flight_id', sa.Integer(), nullable=False))
    op.drop_constraint(None, 'ticekts', type_='foreignkey')
    op.create_foreign_key(None, 'ticekts', 'flights', ['flight_id'], ['id'])
    op.drop_column('ticekts', 'flight')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticekts', sa.Column('flight', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'ticekts', type_='foreignkey')
    op.create_foreign_key(None, 'ticekts', 'flights', ['flight'], ['id'])
    op.drop_column('ticekts', 'flight_id')
    # ### end Alembic commands ###
